import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const destination = path.join(root, 'dist', 'weavemap');
const resources = path.join(destination, 'skills', 'weavemap', 'resources');
fs.mkdirSync(resources, { recursive: true });
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'plugin.json'), 'utf8'));
if (manifest.name !== 'weavemap' || manifest.version !== JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).version) throw new Error('Plugin identity/version mismatch.');
for (const file of ['plugin.json', 'LICENSE']) fs.copyFileSync(path.join(root, file), path.join(destination, file));
fs.copyFileSync(path.join(root, 'skills/weavemap/SKILL.md'), path.join(destination, 'skills/weavemap/SKILL.md'));
const runtime = ['PROTOCOL.md', 'index.html', 'app.js', 'core.js', 'style.css', 'generate_hud.mjs', 'generate_hud.ps1', 'live_server.mjs', 'state.template.js'];
for (const file of runtime) fs.copyFileSync(path.join(root, file), path.join(resources, file));
// Explicit allowlist: never upload this repository's state.js, test outputs,
// dependencies, Git data or a previous build's unrelated files.
const entries = ['weavemap/plugin.json', 'weavemap/LICENSE', 'weavemap/skills/weavemap/SKILL.md', ...runtime.map(file => `weavemap/skills/weavemap/resources/${file}`)];
// Preserve the compatibility overlay generated by Plugin Creator on creation.
fs.mkdirSync(path.join(destination, '.codex-plugin'), { recursive: true });
const overlay = { interface: manifest.extensions['com.openai'].interface, name: manifest.name, version: manifest.version,
  description: manifest.description, author: manifest.author, keywords: [], skills: './skills' };
fs.writeFileSync(path.join(destination, '.codex-plugin/plugin.json'), JSON.stringify(overlay, null, 2) + '\n');
entries.push('weavemap/.codex-plugin/plugin.json');
const archive = path.join(root, 'dist', 'weavemap.tar.gz');
execFileSync('tar', ['-czf', archive, '-C', path.join(root, 'dist'), ...entries]);
const listing = execFileSync('tar', ['-tzf', archive], { encoding: 'utf8' }).trim().split(/\r?\n/);
if (listing.length !== entries.length || listing.some(entry => !entries.includes(entry))) throw new Error('Archive verification failed.');
console.log(`Packaged WeaveMap ${manifest.version}: ${archive} (${listing.length} files)`);
